/**
 * Director Agent Type Definitions
 * 
 * The Director Agent sits between the Arc outline and the Writer (DeepSeek)
 * to generate detailed beat sheets that control pacing and prevent:
 * - Rushing climactic moments
 * - Dragging out filler content
 * - Pacing inconsistencies
 */

/**
 * Beat types for micro-events within a chapter
 */
export type MicroBeatType = 
  | 'setup'        // Establishing scene, characters, or context
  | 'tension'      // Building suspense or conflict
  | 'release'      // Tension release or comic relief
  | 'cliffhanger'  // End-of-chapter hook
  | 'revelation'   // New information revealed
  | 'action'       // Combat, chase, or physical conflict
  | 'reflection'   // Character introspection or dialogue
  | 'escalation'   // Stakes or conflict intensifying
  | 'breakthrough' // Cultivation advancement or skill mastery
  | 'setback'      // Character faces obstacle or failure
  | 'foreshadow';  // Subtle hint at future events

/**
 * A single micro-beat within a chapter
 * The Director generates 5-8 of these per chapter
 */
export interface MicroBeat {
  id: string;
  order: number;
  type: MicroBeatType;
  description: string;
  /** Whether this beat MUST be included (vs optional) */
  mandatory: boolean;
  /** Suggested word count for this beat */
  targetWordCount?: number;
  /** Characters that should appear in this beat */
  charactersInvolved?: string[];
  /** Emotional tone for this beat */
  emotionalTone?: 'tense' | 'hopeful' | 'desperate' | 'triumphant' | 'melancholic' | 'mysterious' | 'comedic';
  /** If this beat progresses a specific thread */
  threadId?: string;
}

/**
 * Pacing guidance for the chapter
 */
export interface PacingGuidance {
  /** Overall pace for this chapter */
  overallPace: 'slow' | 'moderate' | 'fast' | 'breakneck';
  /** Suggested total word count */
  targetWordCount: number;
  /** Minimum word count (don't rush) */
  minimumWordCount: number;
  /** Maximum word count (don't drag) */
  maximumWordCount: number;
  /** Tension level at chapter start (0-100) */
  startingTensionLevel: number;
  /** Target tension level at chapter end (0-100) */
  endingTensionLevel: number;
  /** Should this chapter end on a cliffhanger? */
  requiresCliffhanger: boolean;
  /** Specific pacing notes for the Writer */
  pacingNotes: string[];
}

/**
 * Climax protection prevents premature resolution of major conflicts
 */
export interface ClimaxProtection {
  /** Is this chapter near a climactic moment? */
  isClimaxProximate: boolean;
  /** Threads that should NOT be resolved in this chapter */
  protectedThreadIds: string[];
  /** Conflicts that should NOT be resolved yet */
  protectedConflicts: string[];
  /** Minimum chapters before resolution is allowed */
  minimumChaptersUntilResolution: number;
  /** Warning message for the Writer */
  warningMessage: string;
}

/**
 * Arc position analysis for pacing decisions
 */
export interface ArcPositionAnalysis {
  arcId: string;
  arcTitle: string;
  /** Total target chapters for this arc */
  targetChapters: number;
  /** Current chapter within the arc */
  currentArcChapter: number;
  /** Progress percentage (0-100) */
  progressPercent: number;
  /** Arc phase based on position */
  arcPhase: 'opening' | 'rising_action' | 'midpoint' | 'escalation' | 'climax_approach' | 'climax' | 'resolution';
  /** Remaining checklist items */
  remainingChecklistItems: string[];
  /** Completed checklist items */
  completedChecklistItems: string[];
}

/**
 * The complete beat sheet generated by the Director
 */
export interface DirectorBeatSheet {
  /** Arc this beat sheet belongs to */
  arcId: string;
  arcTitle: string;
  /** Chapter number this beat sheet is for */
  chapterNumber: number;
  /** Arc progress percentage */
  arcProgressPercent: number;
  /** Position analysis */
  arcPosition: ArcPositionAnalysis;
  /** The micro-beats for this chapter (5-8 typically) */
  beats: MicroBeat[];
  /** Pacing guidance */
  pacingGuidance: PacingGuidance;
  /** Climax protection rules */
  climaxProtection?: ClimaxProtection;
  /** Director's reasoning for this beat sheet */
  directorReasoning: string[];
  /** Specific warnings or cautions */
  warnings: string[];
  /** Timestamp */
  createdAt: number;
}

/**
 * Configuration for the Director Agent
 */
export interface DirectorConfig {
  /** Whether Director is enabled */
  enabled: boolean;
  /** Minimum beats per chapter */
  minBeatsPerChapter: number;
  /** Maximum beats per chapter */
  maxBeatsPerChapter: number;
  /** Default target word count per chapter */
  defaultTargetWordCount: number;
  /** Enable climax protection */
  enableClimaxProtection: boolean;
  /** Chapters before climax to start protection */
  climaxProtectionThreshold: number;
  /** Use DeepSeek reasoner for deeper analysis */
  useReasonerMode: boolean;
  /** Temperature for generation */
  temperature: number;
  /** Maximum tokens for response */
  maxTokens: number;
}

/**
 * Default Director configuration
 */
export const DEFAULT_DIRECTOR_CONFIG: DirectorConfig = {
  enabled: true,
  minBeatsPerChapter: 5,
  maxBeatsPerChapter: 8,
  defaultTargetWordCount: 3000,
  enableClimaxProtection: true,
  climaxProtectionThreshold: 3, // Start protecting 3 chapters before climax
  useReasonerMode: false, // Disabled for faster performance (was true)
  temperature: 0.7,
  maxTokens: 4096,
};

/**
 * Result from the Director Agent
 */
export interface DirectorResult {
  success: boolean;
  beatSheet: DirectorBeatSheet | null;
  error?: string;
  durationMs: number;
}

/**
 * Xianxia-specific pacing rules
 */
export interface XianxiaPacingRules {
  /** Never rush cultivation breakthroughs */
  protectBreakthroughs: boolean;
  /** Minimum chapters for tribulation sequences */
  minimumTribulationChapters: number;
  /** Tournament pacing (chapters per round) */
  tournamentChaptersPerRound: number;
  /** Sect tournament minimum chapters */
  sectTournamentMinimumChapters: number;
  /** Alchemy trial minimum chapters */
  alchemyTrialMinimumChapters: number;
  /** Revenge arc minimum chapters before confrontation */
  revengeMinimumBuildUp: number;
}

/**
 * Default Xianxia pacing rules
 */
export const DEFAULT_XIANXIA_PACING_RULES: XianxiaPacingRules = {
  protectBreakthroughs: true,
  minimumTribulationChapters: 2,
  tournamentChaptersPerRound: 2,
  sectTournamentMinimumChapters: 10,
  alchemyTrialMinimumChapters: 5,
  revengeMinimumBuildUp: 15,
};

/**
 * Raw response from the Director AI
 */
export interface DirectorRawResponse {
  beats: Array<{
    type: string;
    description: string;
    mandatory?: boolean;
    targetWordCount?: number;
    charactersInvolved?: string[];
    emotionalTone?: string;
  }>;
  pacingGuidance: {
    overallPace: string;
    targetWordCount: number;
    minimumWordCount?: number;
    maximumWordCount?: number;
    startingTensionLevel: number;
    endingTensionLevel: number;
    requiresCliffhanger?: boolean;
    pacingNotes?: string[];
  };
  climaxProtection?: {
    isClimaxProximate: boolean;
    protectedThreads?: string[];
    protectedConflicts?: string[];
    minimumChaptersUntilResolution?: number;
    warningMessage?: string;
  };
  reasoning: string[];
  warnings?: string[];
}
